services:
  app:
    build:
      context: .
      target: app
    ports:
      - "8080:8080"
    environment:
      - Redis__ConnectionString=redis:6379
      - FotMob__MockMode=${USE_SCRAPER_MOCK_MODE:-false}
      - FotMob__UseFixtureData=${USE_SCRAPER_FIXTURE_DATA:-false}
      - SeedTestUsers=${USE_SCRAPER_MOCK_MODE:-false}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
