services:
  - type: web
    name: farmersleague-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/hello
    envVars:
      - key: PORT
        value: 8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SeedTestUsers
        value: false
      - key: Redis__ConnectionString
        sync: false
      - key: WorldCupScraper__BaseUrl
        fromService:
          type: pserv
          name: farmersleague-scraper
          property: hostport

  - type: pserv
    name: farmersleague-scraper
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.scraper
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FotMob__MockMode
        value: false
      - key: FotMob__UseFixtureData
        value: false
